### ISSUE TITLE
Order_info_all 요청에 param넣을시 Error

### ISSUE THREAD

**Issue by Wollala** [uJhin/upbit-client#46]
아래와 같이 Order_info_all 요청에 param을 넣으면 error 가 발생합니다.
1.3.1.1 버전되면서 발생합니다.
1.3.1.0 에선 정상동작 합니다.

**재현가능한 코드**
```python
from upbit.client import Upbit

access_key = "MY KEY"
secret_key = "MY KEY"

client = Upbit(access_key, secret_key)
resp = client.Order.Order_info_all(states=['done', 'cancel'])
print(resp['result'])
```

**Error log**
```shell
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/parse.py", line 925, in urlencode
    if len(query) and not isinstance(query[0], tuple):
TypeError: object of type 'APIKeyAuthenticator' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myhome/upbit_test/test.py", line 44, in <module>
    resp = client.Order.Order_info_all(state='done')
  File "/home/myhome/upbit_test/.venv/lib/python3.8/site-packages/upbit/models.py", line 454, in Order_info_all
    future = self.__client.Order.Order_info_all(**kwargs)
  File "/home/myhome/upbit_test/.venv/lib/python3.8/site-packages/bravado/client.py", line 276, in __call__
    return http_client.request(
  File "/home/myhome/upbit_test/.venv/lib/python3.8/site-packages/bravado/requests_client.py", line 399, in request
    self.authenticated_request(sanitized_params),
  File "/home/myhome/upbit_test/.venv/lib/python3.8/site-packages/bravado/requests_client.py", line 440, in authenticated_request
    return self.apply_authentication(requests.Request(**request_params))
  File "/home/myhome/upbit_test/.venv/lib/python3.8/site-packages/bravado/requests_client.py", line 445, in apply_authentication
    return self.authenticator.apply(request)
  File "/home/myhome/upbit_test/.venv/lib/python3.8/site-packages/upbit/authentication.py", line 38, in apply
    payload = self.generate_payload(request)
  File "/home/myhome/upbit_test/.venv/lib/python3.8/site-packages/upbit/authentication.py", line 59, in generate_payload
    query = self.generate_query(params)
  File "/home/myhome/upbit_test/.venv/lib/python3.8/site-packages/upbit/authentication.py", line 74, in generate_query
    query = self.urlencode({
  File "/usr/lib/python3.8/urllib/parse.py", line 933, in urlencode
    raise TypeError("not a valid non-string sequence "
  File "/usr/lib/python3.8/urllib/parse.py", line 925, in urlencode
    if len(query) and not isinstance(query[0], tuple):
TypeError: not a valid non-string sequence or mapping object

```

**Comment by uJhin** [comment]
안녕하세요, Upbit Client 개발자입니다.
Upbit OPEN API 1.3.2 버전으로 업데이트 되면서 문의해주신 이슈사항까지 고려하여 수정하였습니다.
#47 를 참고해주시면 감사드리겠습니다.
다시 한번, 발견된 문제점을 문의해주셔서 진심으로 감사드립니다.
